spring:
  application:
    name: category-service

  datasource:
    url: jdbc:postgresql://localhost:5435/category_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql

## old way: work with Spring Cloud Sleuth which was retired after Boot 2.7. so work only below 2.7
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0   # sampler.probability: 1.0 ensures every request is traced (good for debugging). Set to lower in prod.

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

# --- Tracing Configuration ---
management:
  zipkin: # Tell the app where the Zipkin server is
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing: # Sampling probability (1.0 means trace 100% of requests, good for dev)
    sampling:
      probability: 1.0 # 100% of requests traced (reduce in prod, e.g. 0.1)
