spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5436/product_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql

server:
  port: 8084

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

# --- Tracing Configuration ---
management:
  zipkin: # Tell the app where the Zipkin server is
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing: # Sampling probability (1.0 means trace 100% of requests, good for dev)
    sampling:
      probability: 1.0 # 100% of requests traced (reduce in prod, e.g. 0.1)